name: 'Amazon ECS Renew Task Schedule'
description: 'Renew Task Definition for Amazon ECS Task Schedule'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  update-task-definition-arn:
    description: 'ECS task definition arn'
    required: true
  cluster:
    description: 'ECS cluster'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
